from tkinter import *
root =Tk()
root.title("Simple Calculator:")
e = Entry(root,width=35,borderwidth=5)
e.grid(row=0,column=0,columnspan=3,padx=10,pady=10)
#e.pack()
#e.insert(0," Enter the Name : ")
def button_add():
    return
b1=Button(root,text="1",padx=30,pady=10,command=button_add)
b2=Button(root,text="2",padx=30,pady=10,command=button_add)
b3=Button(root,text="3",padx=30,pady=10,command=button_add)
b4=Button(root,text="4",padx=30,pady=10,command=button_add)
b5=Button(root,text="5",padx=30,pady=10,command=button_add)
b6=Button(root,text="6",padx=30,pady=10,command=button_add)
b7=Button(root,text="7",padx=30,pady=10,command=button_add)
b8=Button(root,text="8",padx=30,pady=10,command=button_add)
b9=Button(root,text="9",padx=30,pady=10,command=button_add)
b0=Button(root,text="0",padx=30,pady=10,command=button_add)
b1.grid(row=3,column=0)
b2.grid(row=3,column=1)
b3.grid(row=3,column=2)
b4.grid(row=2,column=0)
b5.grid(row=2,column=1)
b6.grid(row=2,column=2)
b7.grid(row=1,column=0)
b8.grid(row=1,column=1)
b9.grid(row=1,column=2)
b0.grid(row=4,column=1)
plus = Button(root, text=' + ', fg='black',  command=lambda: press("+"), height=1, width=7) 
plus.grid(row=5, column=0) 
minus = Button(root, text=' - ', fg='black',command=lambda: press("-"), height=1, width=7) 
minus.grid(row=3, column=3)  
multiply = Button(root, text=' * ', fg='black',  command=lambda: press("*"), height=1, width=7) 
multiply.grid(row=4, column=3)  
divide = Button(root, text=' / ', fg='black',  command=lambda: press("/"), height=1, width=7) 
divide.grid(row=5, column=3)  
equal = Button(root, text=' = ', fg='black', command=button_add, height=1, width=7)
equal.grid(row=5, column=2) 
clear = Button(root, text='Clear', fg='black', command=button_add, height=1, width=7) 
clear.grid(row=5, column='1') 
root.mainloop()
 
